% MPC_Project_FORCESPRO - a fast solver generated by FORCESPRO v5.1.0
%
%   OUTPUT = MPC_Project_FORCESPRO(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.xinit - column vector of length 3
%       PARAMS.linear_model1 - matrix of size [3 x 5]
%       PARAMS.linear_model2 - matrix of size [3 x 5]
%       PARAMS.linear_model3 - matrix of size [3 x 5]
%       PARAMS.linear_model4 - matrix of size [3 x 5]
%       PARAMS.linear_model5 - matrix of size [3 x 5]
%       PARAMS.linear_model6 - matrix of size [3 x 5]
%       PARAMS.linear_model7 - matrix of size [3 x 5]
%       PARAMS.linear_model8 - matrix of size [3 x 5]
%       PARAMS.linear_model9 - matrix of size [3 x 5]
%       PARAMS.linear_model10 - matrix of size [3 x 5]
%       PARAMS.linear_model11 - matrix of size [3 x 5]
%       PARAMS.linear_model12 - matrix of size [3 x 5]
%       PARAMS.linear_model13 - matrix of size [3 x 5]
%       PARAMS.linear_model14 - matrix of size [3 x 5]
%       PARAMS.linear_model15 - matrix of size [3 x 5]
%       PARAMS.linear_model16 - matrix of size [3 x 5]
%       PARAMS.linear_model17 - matrix of size [3 x 5]
%       PARAMS.linear_model18 - matrix of size [3 x 5]
%       PARAMS.linear_model19 - matrix of size [3 x 5]
%       PARAMS.linear_model20 - matrix of size [3 x 5]
%       PARAMS.linear_model21 - matrix of size [3 x 5]
%       PARAMS.linear_model22 - matrix of size [3 x 5]
%       PARAMS.linear_model23 - matrix of size [3 x 5]
%       PARAMS.linear_model24 - matrix of size [3 x 5]
%       PARAMS.linear_model25 - matrix of size [3 x 5]
%       PARAMS.linear_model26 - matrix of size [3 x 5]
%       PARAMS.linear_model27 - matrix of size [3 x 5]
%       PARAMS.linear_model28 - matrix of size [3 x 5]
%       PARAMS.linear_model29 - matrix of size [3 x 5]
%       PARAMS.linear_model30 - matrix of size [3 x 5]
%       PARAMS.linear_model31 - matrix of size [3 x 5]
%       PARAMS.linear_model32 - matrix of size [3 x 5]
%       PARAMS.linear_model33 - matrix of size [3 x 5]
%       PARAMS.linear_model34 - matrix of size [3 x 5]
%       PARAMS.linear_model35 - matrix of size [3 x 5]
%       PARAMS.linear_model36 - matrix of size [3 x 5]
%       PARAMS.linear_model37 - matrix of size [3 x 5]
%       PARAMS.linear_model38 - matrix of size [3 x 5]
%       PARAMS.linear_model39 - matrix of size [3 x 5]
%       PARAMS.f_error1 - column vector of length 5
%       PARAMS.f_error2 - column vector of length 5
%       PARAMS.f_error3 - column vector of length 5
%       PARAMS.f_error4 - column vector of length 5
%       PARAMS.f_error5 - column vector of length 5
%       PARAMS.f_error6 - column vector of length 5
%       PARAMS.f_error7 - column vector of length 5
%       PARAMS.f_error8 - column vector of length 5
%       PARAMS.f_error9 - column vector of length 5
%       PARAMS.f_error10 - column vector of length 5
%       PARAMS.f_error11 - column vector of length 5
%       PARAMS.f_error12 - column vector of length 5
%       PARAMS.f_error13 - column vector of length 5
%       PARAMS.f_error14 - column vector of length 5
%       PARAMS.f_error15 - column vector of length 5
%       PARAMS.f_error16 - column vector of length 5
%       PARAMS.f_error17 - column vector of length 5
%       PARAMS.f_error18 - column vector of length 5
%       PARAMS.f_error19 - column vector of length 5
%       PARAMS.f_error20 - column vector of length 5
%       PARAMS.f_error21 - column vector of length 5
%       PARAMS.f_error22 - column vector of length 5
%       PARAMS.f_error23 - column vector of length 5
%       PARAMS.f_error24 - column vector of length 5
%       PARAMS.f_error25 - column vector of length 5
%       PARAMS.f_error26 - column vector of length 5
%       PARAMS.f_error27 - column vector of length 5
%       PARAMS.f_error28 - column vector of length 5
%       PARAMS.f_error29 - column vector of length 5
%       PARAMS.f_error30 - column vector of length 5
%       PARAMS.f_error31 - column vector of length 5
%       PARAMS.f_error32 - column vector of length 5
%       PARAMS.f_error33 - column vector of length 5
%       PARAMS.f_error34 - column vector of length 5
%       PARAMS.f_error35 - column vector of length 5
%       PARAMS.f_error36 - column vector of length 5
%       PARAMS.f_error37 - column vector of length 5
%       PARAMS.f_error38 - column vector of length 5
%       PARAMS.f_error39 - column vector of length 5
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.output - column vector of size 50
%
%   [OUTPUT, EXITFLAG] = MPC_Project_FORCESPRO(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = MPC_Project_FORCESPRO(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING
