/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCENLPsolver_model_ ## ID
#endif

#include <math.h> 
#include "FORCENLPsolver_model.h"

#ifndef casadi_real
#define casadi_real FORCENLPsolver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[12] = {1, 5, 0, 1, 2, 3, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s4[18] = {3, 5, 0, 2, 5, 6, 7, 10, 0, 1, 0, 1, 2, 0, 1, 0, 1, 2};
static const casadi_int casadi_s5[10] = {1, 5, 0, 0, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s6[13] = {1, 5, 0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0};

/* FORCENLPsolver_objective_0:(i0[5],i1[3])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[1]? arg[1][1] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=1.0000000000000001e-001;
  a1=arg[0]? arg[0][0] : 0;
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a3=(a3+a1);
  a1=arg[0]? arg[0][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

int FORCENLPsolver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCENLPsolver_objective_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_objective_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_objective_0_free_mem(int mem) {
}

int FORCENLPsolver_objective_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_objective_0_release(int mem) {
}

void FORCENLPsolver_objective_0_incref(void) {
}

void FORCENLPsolver_objective_0_decref(void) {
}

casadi_int FORCENLPsolver_objective_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_objective_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCENLPsolver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dobjective_0:(i0[5],i1[3])->(o0[1x5,4nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=1.0000000000000001e-001;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a2=(a3-a1);
  a2=(a0*a2);
  a3=(a3-a1);
  a0=(a0*a3);
  a2=(a2+a0);
  if (res[0]!=0) res[0][3]=a2;
  return 0;
}

int FORCENLPsolver_dobjective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCENLPsolver_dobjective_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dobjective_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dobjective_0_free_mem(int mem) {
}

int FORCENLPsolver_dobjective_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_dobjective_0_release(int mem) {
}

void FORCENLPsolver_dobjective_0_incref(void) {
}

void FORCENLPsolver_dobjective_0_decref(void) {
}

casadi_int FORCENLPsolver_dobjective_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dobjective_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dobjective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCENLPsolver_dobjective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dynamics_0:(i0[5],i1[3])->(o0[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=8.3333333333333339e-004;
  a2=arg[0]? arg[0][0] : 0;
  a3=arg[0]? arg[0][4] : 0;
  a4=cos(a3);
  a4=(a2*a4);
  a5=2.;
  a6=2.5000000000000001e-003;
  a7=arg[0]? arg[0][1] : 0;
  a8=(a6*a7);
  a8=(a3+a8);
  a9=cos(a8);
  a9=(a2*a9);
  a9=(a5*a9);
  a4=(a4+a9);
  a6=(a6*a7);
  a6=(a3+a6);
  a9=cos(a6);
  a9=(a2*a9);
  a9=(a5*a9);
  a4=(a4+a9);
  a9=5.0000000000000001e-003;
  a9=(a9*a7);
  a9=(a3+a9);
  a10=cos(a9);
  a10=(a2*a10);
  a4=(a4+a10);
  a4=(a1*a4);
  a0=(a0+a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a4=sin(a3);
  a4=(a2*a4);
  a8=sin(a8);
  a8=(a2*a8);
  a8=(a5*a8);
  a4=(a4+a8);
  a6=sin(a6);
  a6=(a2*a6);
  a6=(a5*a6);
  a4=(a4+a6);
  a9=sin(a9);
  a2=(a2*a9);
  a4=(a4+a2);
  a4=(a1*a4);
  a0=(a0+a4);
  if (res[0]!=0) res[0][1]=a0;
  a0=(a5*a7);
  a0=(a7+a0);
  a5=(a5*a7);
  a0=(a0+a5);
  a0=(a0+a7);
  a1=(a1*a0);
  a3=(a3+a1);
  if (res[0]!=0) res[0][2]=a3;
  return 0;
}

int FORCENLPsolver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCENLPsolver_dynamics_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dynamics_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dynamics_0_free_mem(int mem) {
}

int FORCENLPsolver_dynamics_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_dynamics_0_release(int mem) {
}

void FORCENLPsolver_dynamics_0_incref(void) {
}

void FORCENLPsolver_dynamics_0_decref(void) {
}

casadi_int FORCENLPsolver_dynamics_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dynamics_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

int FORCENLPsolver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_ddynamics_0:(i0[5],i1[3])->(o0[3x5,10nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=8.3333333333333339e-004;
  a1=arg[0]? arg[0][4] : 0;
  a2=cos(a1);
  a3=2.;
  a4=2.5000000000000001e-003;
  a5=arg[0]? arg[0][1] : 0;
  a6=(a4*a5);
  a6=(a1+a6);
  a7=cos(a6);
  a7=(a3*a7);
  a2=(a2+a7);
  a7=(a4*a5);
  a7=(a1+a7);
  a8=cos(a7);
  a8=(a3*a8);
  a2=(a2+a8);
  a8=5.0000000000000001e-003;
  a5=(a8*a5);
  a5=(a1+a5);
  a9=cos(a5);
  a2=(a2+a9);
  a2=(a0*a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=sin(a1);
  a9=sin(a6);
  a9=(a3*a9);
  a2=(a2+a9);
  a9=sin(a7);
  a9=(a3*a9);
  a2=(a2+a9);
  a9=sin(a5);
  a2=(a2+a9);
  a2=(a0*a2);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[0]? arg[0][0] : 0;
  a9=sin(a6);
  a10=(a4*a9);
  a10=(a2*a10);
  a10=(a3*a10);
  a11=sin(a7);
  a12=(a4*a11);
  a12=(a2*a12);
  a12=(a3*a12);
  a10=(a10+a12);
  a12=sin(a5);
  a13=(a8*a12);
  a13=(a2*a13);
  a10=(a10+a13);
  a10=(a0*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][2]=a10;
  a6=cos(a6);
  a10=(a4*a6);
  a10=(a2*a10);
  a10=(a3*a10);
  a7=cos(a7);
  a4=(a4*a7);
  a4=(a2*a4);
  a4=(a3*a4);
  a10=(a10+a4);
  a5=cos(a5);
  a4=(a8*a5);
  a4=(a2*a4);
  a10=(a10+a4);
  a10=(a0*a10);
  if (res[0]!=0) res[0][3]=a10;
  if (res[0]!=0) res[0][4]=a8;
  a8=1.;
  if (res[0]!=0) res[0][5]=a8;
  if (res[0]!=0) res[0][6]=a8;
  a10=sin(a1);
  a10=(a2*a10);
  a9=(a2*a9);
  a9=(a3*a9);
  a10=(a10+a9);
  a11=(a2*a11);
  a11=(a3*a11);
  a10=(a10+a11);
  a12=(a2*a12);
  a10=(a10+a12);
  a10=(a0*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][7]=a10;
  a1=cos(a1);
  a1=(a2*a1);
  a6=(a2*a6);
  a6=(a3*a6);
  a1=(a1+a6);
  a7=(a2*a7);
  a3=(a3*a7);
  a1=(a1+a3);
  a2=(a2*a5);
  a1=(a1+a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a8;
  return 0;
}

int FORCENLPsolver_ddynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCENLPsolver_ddynamics_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_ddynamics_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_ddynamics_0_free_mem(int mem) {
}

int FORCENLPsolver_ddynamics_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_ddynamics_0_release(int mem) {
}

void FORCENLPsolver_ddynamics_0_incref(void) {
}

void FORCENLPsolver_ddynamics_0_decref(void) {
}

casadi_int FORCENLPsolver_ddynamics_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_ddynamics_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_ddynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_ddynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_ddynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_ddynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_ddynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

int FORCENLPsolver_ddynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_inequalities_0:(i0[5],i1[3])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][2] : 0;
  a1=5.;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a1=arg[0]? arg[0][3] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

int FORCENLPsolver_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCENLPsolver_inequalities_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_inequalities_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_inequalities_0_free_mem(int mem) {
}

int FORCENLPsolver_inequalities_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_inequalities_0_release(int mem) {
}

void FORCENLPsolver_inequalities_0_incref(void) {
}

void FORCENLPsolver_inequalities_0_decref(void) {
}

casadi_int FORCENLPsolver_inequalities_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_inequalities_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCENLPsolver_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dinequalities_0:(i0[5],i1[3])->(o0[1x5,2nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][2] : 0;
  a1=5.;
  a0=(a0-a1);
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

int FORCENLPsolver_dinequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCENLPsolver_dinequalities_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dinequalities_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dinequalities_0_free_mem(int mem) {
}

int FORCENLPsolver_dinequalities_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_dinequalities_0_release(int mem) {
}

void FORCENLPsolver_dinequalities_0_incref(void) {
}

void FORCENLPsolver_dinequalities_0_decref(void) {
}

casadi_int FORCENLPsolver_dinequalities_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dinequalities_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dinequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dinequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dinequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dinequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dinequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

int FORCENLPsolver_dinequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_objective_1:(i0[5],i1[3])->(o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=500.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[1]? arg[1][1] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=100.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][2] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=1.0000000000000001e-001;
  a1=arg[0]? arg[0][0] : 0;
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a3=(a3+a1);
  a1=arg[0]? arg[0][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

int FORCENLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

int FORCENLPsolver_objective_1_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_objective_1_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_objective_1_free_mem(int mem) {
}

int FORCENLPsolver_objective_1_checkout(void) {
  return 0;
}

void FORCENLPsolver_objective_1_release(int mem) {
}

void FORCENLPsolver_objective_1_incref(void) {
}

void FORCENLPsolver_objective_1_decref(void) {
}

casadi_int FORCENLPsolver_objective_1_n_in(void) { return 2;}

casadi_int FORCENLPsolver_objective_1_n_out(void) { return 1;}

casadi_real FORCENLPsolver_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCENLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dobjective_1:(i0[5],i1[3])->(o0[1x5]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=1.0000000000000001e-001;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=500.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a2=(a3-a1);
  a2=(a0*a2);
  a3=(a3-a1);
  a0=(a0*a3);
  a2=(a2+a0);
  if (res[0]!=0) res[0][3]=a2;
  a2=100.;
  a0=arg[0]? arg[0][4] : 0;
  a3=arg[1]? arg[1][2] : 0;
  a1=(a0-a3);
  a1=(a2*a1);
  a0=(a0-a3);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][4]=a1;
  return 0;
}

int FORCENLPsolver_dobjective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

int FORCENLPsolver_dobjective_1_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dobjective_1_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dobjective_1_free_mem(int mem) {
}

int FORCENLPsolver_dobjective_1_checkout(void) {
  return 0;
}

void FORCENLPsolver_dobjective_1_release(int mem) {
}

void FORCENLPsolver_dobjective_1_incref(void) {
}

void FORCENLPsolver_dobjective_1_decref(void) {
}

casadi_int FORCENLPsolver_dobjective_1_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dobjective_1_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dobjective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

int FORCENLPsolver_dobjective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_inequalities_1:(i0[5],i1[3])->(o0) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][2] : 0;
  a1=5.;
  a0=(a0-a1);
  a0=casadi_sq(a0);
  a1=arg[0]? arg[0][3] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

int FORCENLPsolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

int FORCENLPsolver_inequalities_1_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_inequalities_1_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_inequalities_1_free_mem(int mem) {
}

int FORCENLPsolver_inequalities_1_checkout(void) {
  return 0;
}

void FORCENLPsolver_inequalities_1_release(int mem) {
}

void FORCENLPsolver_inequalities_1_incref(void) {
}

void FORCENLPsolver_inequalities_1_decref(void) {
}

casadi_int FORCENLPsolver_inequalities_1_n_in(void) { return 2;}

casadi_int FORCENLPsolver_inequalities_1_n_out(void) { return 1;}

casadi_real FORCENLPsolver_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCENLPsolver_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dinequalities_1:(i0[5],i1[3])->(o0[1x5,2nz]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][2] : 0;
  a1=5.;
  a0=(a0-a1);
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

int FORCENLPsolver_dinequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

int FORCENLPsolver_dinequalities_1_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dinequalities_1_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dinequalities_1_free_mem(int mem) {
}

int FORCENLPsolver_dinequalities_1_checkout(void) {
  return 0;
}

void FORCENLPsolver_dinequalities_1_release(int mem) {
}

void FORCENLPsolver_dinequalities_1_incref(void) {
}

void FORCENLPsolver_dinequalities_1_decref(void) {
}

casadi_int FORCENLPsolver_dinequalities_1_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dinequalities_1_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dinequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dinequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dinequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dinequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dinequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

int FORCENLPsolver_dinequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
