/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCENLPsolver_model_ ## ID
#endif

#include <math.h> 
#include "FORCENLPsolver_model.h"

#ifndef casadi_real
#define casadi_real FORCENLPsolver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[13] = {1, 5, 0, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[18] = {3, 5, 0, 2, 5, 6, 7, 10, 0, 1, 0, 1, 2, 0, 1, 0, 1, 2};

/* FORCENLPsolver_objective_0:(i0[5],i1[3])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[1]? arg[1][1] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=10.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][2] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][0] : 0;
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a3=(a3+a1);
  a1=arg[0]? arg[0][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

int FORCENLPsolver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCENLPsolver_objective_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_objective_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_objective_0_free_mem(int mem) {
}

int FORCENLPsolver_objective_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_objective_0_release(int mem) {
}

void FORCENLPsolver_objective_0_incref(void) {
}

void FORCENLPsolver_objective_0_decref(void) {
}

casadi_int FORCENLPsolver_objective_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_objective_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCENLPsolver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dobjective_0:(i0[5],i1[3])->(o0[1x5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a2=(a3-a1);
  a2=(a0*a2);
  a3=(a3-a1);
  a0=(a0*a3);
  a2=(a2+a0);
  if (res[0]!=0) res[0][3]=a2;
  a2=10.;
  a0=arg[0]? arg[0][4] : 0;
  a3=arg[1]? arg[1][2] : 0;
  a1=(a0-a3);
  a1=(a2*a1);
  a0=(a0-a3);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][4]=a1;
  return 0;
}

int FORCENLPsolver_dobjective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCENLPsolver_dobjective_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dobjective_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dobjective_0_free_mem(int mem) {
}

int FORCENLPsolver_dobjective_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_dobjective_0_release(int mem) {
}

void FORCENLPsolver_dobjective_0_incref(void) {
}

void FORCENLPsolver_dobjective_0_decref(void) {
}

casadi_int FORCENLPsolver_dobjective_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dobjective_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dobjective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCENLPsolver_dobjective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dynamics_0:(i0[5],i1[3])->(o0[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=8.3333333333333332e-03;
  a2=5.0000000000000003e-02;
  a3=arg[0]? arg[0][0] : 0;
  a4=arg[0]? arg[0][4] : 0;
  a5=cos(a4);
  a5=(a3*a5);
  a5=(a2*a5);
  a5=(a0+a5);
  a6=2.;
  a7=2.5000000000000001e-02;
  a8=(a7*a5);
  a8=(a0+a8);
  a9=arg[0]? arg[0][1] : 0;
  a10=(a2*a9);
  a11=sin(a10);
  a10=cos(a10);
  a11=atan2(a11,a10);
  a11=(a4+a11);
  a10=sin(a11);
  a11=cos(a11);
  a10=atan2(a10,a11);
  a11=(a7*a10);
  a11=(a4+a11);
  a12=cos(a11);
  a12=(a3*a12);
  a12=(a2*a12);
  a8=(a8+a12);
  a12=(a6*a8);
  a5=(a5+a12);
  a8=(a7*a8);
  a8=(a0+a8);
  a12=(a2*a9);
  a13=sin(a12);
  a12=cos(a12);
  a13=atan2(a13,a12);
  a13=(a11+a13);
  a12=sin(a13);
  a13=cos(a13);
  a12=atan2(a12,a13);
  a13=(a7*a12);
  a13=(a4+a13);
  a14=cos(a13);
  a14=(a3*a14);
  a14=(a2*a14);
  a8=(a8+a14);
  a14=(a6*a8);
  a5=(a5+a14);
  a8=(a2*a8);
  a8=(a0+a8);
  a14=(a2*a9);
  a15=sin(a14);
  a14=cos(a14);
  a15=atan2(a15,a14);
  a15=(a13+a15);
  a14=sin(a15);
  a15=cos(a15);
  a14=atan2(a14,a15);
  a15=(a2*a14);
  a15=(a4+a15);
  a16=cos(a15);
  a16=(a3*a16);
  a16=(a2*a16);
  a8=(a8+a16);
  a5=(a5+a8);
  a5=(a1*a5);
  a0=(a0+a5);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a5=sin(a4);
  a5=(a3*a5);
  a5=(a2*a5);
  a5=(a0+a5);
  a8=(a7*a5);
  a8=(a0+a8);
  a11=sin(a11);
  a11=(a3*a11);
  a11=(a2*a11);
  a8=(a8+a11);
  a11=(a6*a8);
  a5=(a5+a11);
  a7=(a7*a8);
  a7=(a0+a7);
  a13=sin(a13);
  a13=(a3*a13);
  a13=(a2*a13);
  a7=(a7+a13);
  a13=(a6*a7);
  a5=(a5+a13);
  a7=(a2*a7);
  a7=(a0+a7);
  a13=sin(a15);
  a3=(a3*a13);
  a3=(a2*a3);
  a7=(a7+a3);
  a5=(a5+a7);
  a5=(a1*a5);
  a0=(a0+a5);
  if (res[0]!=0) res[0][1]=a0;
  a12=(a6*a12);
  a10=(a10+a12);
  a6=(a6*a14);
  a10=(a10+a6);
  a2=(a2*a9);
  a9=sin(a2);
  a2=cos(a2);
  a9=atan2(a9,a2);
  a15=(a15+a9);
  a9=sin(a15);
  a15=cos(a15);
  a9=atan2(a9,a15);
  a10=(a10+a9);
  a1=(a1*a10);
  a4=(a4+a1);
  if (res[0]!=0) res[0][2]=a4;
  return 0;
}

int FORCENLPsolver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCENLPsolver_dynamics_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dynamics_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dynamics_0_free_mem(int mem) {
}

int FORCENLPsolver_dynamics_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_dynamics_0_release(int mem) {
}

void FORCENLPsolver_dynamics_0_incref(void) {
}

void FORCENLPsolver_dynamics_0_decref(void) {
}

casadi_int FORCENLPsolver_dynamics_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dynamics_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

int FORCENLPsolver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_ddynamics_0:(i0[5],i1[3])->(o0[3x5,10nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6, a7, a8, a9;
  a0=8.3333333333333332e-03;
  a1=5.0000000000000003e-02;
  a2=arg[0]? arg[0][4] : 0;
  a3=cos(a2);
  a3=(a1*a3);
  a4=2.;
  a5=2.5000000000000001e-02;
  a6=(a5*a3);
  a7=arg[0]? arg[0][1] : 0;
  a8=(a1*a7);
  a9=sin(a8);
  a10=cos(a8);
  a11=atan2(a9,a10);
  a11=(a2+a11);
  a12=sin(a11);
  a13=cos(a11);
  a14=atan2(a12,a13);
  a14=(a5*a14);
  a14=(a2+a14);
  a15=cos(a14);
  a15=(a1*a15);
  a6=(a6+a15);
  a15=(a4*a6);
  a3=(a3+a15);
  a6=(a5*a6);
  a15=(a1*a7);
  a16=sin(a15);
  a17=cos(a15);
  a18=atan2(a16,a17);
  a18=(a14+a18);
  a19=sin(a18);
  a20=cos(a18);
  a21=atan2(a19,a20);
  a21=(a5*a21);
  a21=(a2+a21);
  a22=cos(a21);
  a22=(a1*a22);
  a6=(a6+a22);
  a22=(a4*a6);
  a3=(a3+a22);
  a6=(a1*a6);
  a22=(a1*a7);
  a23=sin(a22);
  a24=cos(a22);
  a25=atan2(a23,a24);
  a25=(a21+a25);
  a26=sin(a25);
  a27=cos(a25);
  a28=atan2(a26,a27);
  a28=(a1*a28);
  a28=(a2+a28);
  a29=cos(a28);
  a29=(a1*a29);
  a6=(a6+a29);
  a3=(a3+a6);
  a3=(a0*a3);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a2);
  a3=(a1*a3);
  a6=(a5*a3);
  a29=sin(a14);
  a29=(a1*a29);
  a6=(a6+a29);
  a29=(a4*a6);
  a3=(a3+a29);
  a6=(a5*a6);
  a29=sin(a21);
  a29=(a1*a29);
  a6=(a6+a29);
  a29=(a4*a6);
  a3=(a3+a29);
  a6=(a1*a6);
  a29=sin(a28);
  a29=(a1*a29);
  a6=(a6+a29);
  a3=(a3+a6);
  a3=(a0*a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0]? arg[0][0] : 0;
  a6=sin(a14);
  a29=cos(a11);
  a30=cos(a8);
  a30=(a1*a30);
  a10=(a10*a30);
  a8=sin(a8);
  a8=(a1*a8);
  a9=(a9*a8);
  a10=(a10+a9);
  a29=(a29*a10);
  a13=(a13*a29);
  a11=sin(a11);
  a11=(a11*a10);
  a12=(a12*a11);
  a13=(a13+a12);
  a12=(a5*a13);
  a11=(a6*a12);
  a11=(a3*a11);
  a11=(a1*a11);
  a10=(a4*a11);
  a11=(a5*a11);
  a29=sin(a21);
  a9=cos(a18);
  a8=cos(a15);
  a8=(a1*a8);
  a17=(a17*a8);
  a15=sin(a15);
  a15=(a1*a15);
  a16=(a16*a15);
  a17=(a17+a16);
  a17=(a12+a17);
  a16=(a9*a17);
  a16=(a20*a16);
  a18=sin(a18);
  a17=(a18*a17);
  a17=(a19*a17);
  a16=(a16+a17);
  a17=(a5*a16);
  a15=(a29*a17);
  a15=(a3*a15);
  a15=(a1*a15);
  a11=(a11+a15);
  a15=(a4*a11);
  a10=(a10+a15);
  a11=(a1*a11);
  a15=sin(a28);
  a8=cos(a25);
  a30=cos(a22);
  a30=(a1*a30);
  a24=(a24*a30);
  a22=sin(a22);
  a22=(a1*a22);
  a23=(a23*a22);
  a24=(a24+a23);
  a24=(a17+a24);
  a23=(a8*a24);
  a23=(a27*a23);
  a25=sin(a25);
  a24=(a25*a24);
  a24=(a26*a24);
  a23=(a23+a24);
  a24=(a1*a23);
  a22=(a15*a24);
  a22=(a3*a22);
  a22=(a1*a22);
  a11=(a11+a22);
  a10=(a10+a11);
  a10=(a0*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][2]=a10;
  a14=cos(a14);
  a12=(a14*a12);
  a12=(a3*a12);
  a12=(a1*a12);
  a10=(a4*a12);
  a12=(a5*a12);
  a21=cos(a21);
  a17=(a21*a17);
  a17=(a3*a17);
  a17=(a1*a17);
  a12=(a12+a17);
  a17=(a4*a12);
  a10=(a10+a17);
  a12=(a1*a12);
  a17=cos(a28);
  a11=(a17*a24);
  a11=(a3*a11);
  a11=(a1*a11);
  a12=(a12+a11);
  a10=(a10+a12);
  a10=(a0*a10);
  if (res[0]!=0) res[0][3]=a10;
  a16=(a4*a16);
  a13=(a13+a16);
  a23=(a4*a23);
  a13=(a13+a23);
  a7=(a1*a7);
  a23=sin(a7);
  a16=cos(a7);
  a10=atan2(a23,a16);
  a28=(a28+a10);
  a10=cos(a28);
  a12=cos(a28);
  a11=cos(a7);
  a11=(a1*a11);
  a16=(a16*a11);
  a7=sin(a7);
  a7=(a1*a7);
  a23=(a23*a7);
  a16=(a16+a23);
  a24=(a24+a16);
  a16=(a12*a24);
  a16=(a10*a16);
  a23=sin(a28);
  a28=sin(a28);
  a24=(a28*a24);
  a24=(a23*a24);
  a16=(a16+a24);
  a13=(a13+a16);
  a13=(a0*a13);
  if (res[0]!=0) res[0][4]=a13;
  a13=1.0512710937500001e+00;
  if (res[0]!=0) res[0][5]=a13;
  if (res[0]!=0) res[0][6]=a13;
  a13=sin(a2);
  a13=(a3*a13);
  a13=(a1*a13);
  a16=(a5*a13);
  a24=1.0249999999999999e+00;
  a6=(a24*a6);
  a6=(a3*a6);
  a6=(a1*a6);
  a16=(a16+a6);
  a6=(a4*a16);
  a13=(a13+a6);
  a16=(a5*a16);
  a6=1.;
  a9=(a24*a9);
  a20=(a20*a9);
  a18=(a24*a18);
  a19=(a19*a18);
  a20=(a20+a19);
  a19=(a5*a20);
  a19=(a6+a19);
  a29=(a29*a19);
  a29=(a3*a29);
  a29=(a1*a29);
  a16=(a16+a29);
  a29=(a4*a16);
  a13=(a13+a29);
  a16=(a1*a16);
  a8=(a8*a19);
  a27=(a27*a8);
  a25=(a25*a19);
  a26=(a26*a25);
  a27=(a27+a26);
  a26=(a1*a27);
  a26=(a6+a26);
  a15=(a15*a26);
  a15=(a3*a15);
  a15=(a1*a15);
  a16=(a16+a15);
  a13=(a13+a16);
  a13=(a0*a13);
  a13=(-a13);
  if (res[0]!=0) res[0][7]=a13;
  a2=cos(a2);
  a2=(a3*a2);
  a2=(a1*a2);
  a13=(a5*a2);
  a24=(a24*a14);
  a24=(a3*a24);
  a24=(a1*a24);
  a13=(a13+a24);
  a24=(a4*a13);
  a2=(a2+a24);
  a5=(a5*a13);
  a21=(a21*a19);
  a21=(a3*a21);
  a21=(a1*a21);
  a5=(a5+a21);
  a21=(a4*a5);
  a2=(a2+a21);
  a5=(a1*a5);
  a17=(a17*a26);
  a3=(a3*a17);
  a1=(a1*a3);
  a5=(a5+a1);
  a2=(a2+a5);
  a2=(a0*a2);
  if (res[0]!=0) res[0][8]=a2;
  a20=(a4*a20);
  a20=(a6+a20);
  a4=(a4*a27);
  a20=(a20+a4);
  a12=(a12*a26);
  a10=(a10*a12);
  a28=(a28*a26);
  a23=(a23*a28);
  a10=(a10+a23);
  a20=(a20+a10);
  a0=(a0*a20);
  a6=(a6+a0);
  if (res[0]!=0) res[0][9]=a6;
  return 0;
}

int FORCENLPsolver_ddynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCENLPsolver_ddynamics_0_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_ddynamics_0_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_ddynamics_0_free_mem(int mem) {
}

int FORCENLPsolver_ddynamics_0_checkout(void) {
  return 0;
}

void FORCENLPsolver_ddynamics_0_release(int mem) {
}

void FORCENLPsolver_ddynamics_0_incref(void) {
}

void FORCENLPsolver_ddynamics_0_decref(void) {
}

casadi_int FORCENLPsolver_ddynamics_0_n_in(void) { return 2;}

casadi_int FORCENLPsolver_ddynamics_0_n_out(void) { return 1;}

casadi_real FORCENLPsolver_ddynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_ddynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_ddynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_ddynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_ddynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

int FORCENLPsolver_ddynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_objective_1:(i0[5],i1[3])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][3] : 0;
  a2=arg[1]? arg[1][1] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=10.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][2] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][0] : 0;
  a1=casadi_sq(a1);
  a1=(a0*a1);
  a3=(a3+a1);
  a1=arg[0]? arg[0][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

int FORCENLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCENLPsolver_objective_1_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_objective_1_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_objective_1_free_mem(int mem) {
}

int FORCENLPsolver_objective_1_checkout(void) {
  return 0;
}

void FORCENLPsolver_objective_1_release(int mem) {
}

void FORCENLPsolver_objective_1_incref(void) {
}

void FORCENLPsolver_objective_1_decref(void) {
}

casadi_int FORCENLPsolver_objective_1_n_in(void) { return 2;}

casadi_int FORCENLPsolver_objective_1_n_out(void) { return 1;}

casadi_real FORCENLPsolver_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int FORCENLPsolver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCENLPsolver_dobjective_1:(i0[5],i1[3])->(o0[1x5]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][0] : 0;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a1+a1);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=100.;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a2=(a3-a1);
  a2=(a0*a2);
  a3=(a3-a1);
  a0=(a0*a3);
  a2=(a2+a0);
  if (res[0]!=0) res[0][3]=a2;
  a2=10.;
  a0=arg[0]? arg[0][4] : 0;
  a3=arg[1]? arg[1][2] : 0;
  a1=(a0-a3);
  a1=(a2*a1);
  a0=(a0-a3);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][4]=a1;
  return 0;
}

int FORCENLPsolver_dobjective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCENLPsolver_dobjective_1_alloc_mem(void) {
  return 0;
}

int FORCENLPsolver_dobjective_1_init_mem(int mem) {
  return 0;
}

void FORCENLPsolver_dobjective_1_free_mem(int mem) {
}

int FORCENLPsolver_dobjective_1_checkout(void) {
  return 0;
}

void FORCENLPsolver_dobjective_1_release(int mem) {
}

void FORCENLPsolver_dobjective_1_incref(void) {
}

void FORCENLPsolver_dobjective_1_decref(void) {
}

casadi_int FORCENLPsolver_dobjective_1_n_in(void) { return 2;}

casadi_int FORCENLPsolver_dobjective_1_n_out(void) { return 1;}

casadi_real FORCENLPsolver_dobjective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCENLPsolver_dobjective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCENLPsolver_dobjective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

int FORCENLPsolver_dobjective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
